#:schema node_modules/wrangler/config-schema.json
name = "clog-service"
main = "src/index.ts"
compatibility_date = "2025-01-09"

[observability]
enabled = true


[env.staging]

vars = { ENVIRONMENT = "staging" }

d1_databases = [
	{ binding = "DB", database_name = "clog-db-staging", database_id = "6fd53577-3689-4c3c-8266-63f1407d559a" },
]


[env.production]

vars = { ENVIRONMENT = "production" }

d1_databases = [
	{ binding = "DB", database_name = "clog-db-prod", database_id = "f55456df-b2aa-431e-b7d6-fae1e0ceee13" },
]
