#:schema node_modules/wrangler/config-schema.json
name = "clog"
route = { pattern = "clog.timothylin.me", custom_domain = true }
main = "src/service.ts"
compatibility_date = "2025-01-09"
assets = { directory = "./dist" }

[observability]
enabled = true


[env.staging]

route = { pattern = "staging.clog.timothylin.me", custom_domain = true }

vars = { ENVIRONMENT = "staging" }

d1_databases = [
	{ binding = "DB", database_name = "clog-db-staging", database_id = "6fd53577-3689-4c3c-8266-63f1407d559a" },
]


[env.prod]

vars = { ENVIRONMENT = "prod" }

d1_databases = [
	{ binding = "DB", database_name = "clog-db-prod", database_id = "f55456df-b2aa-431e-b7d6-fae1e0ceee13" },
]
